name: BUPLAY
description: A Gamified Platform for students

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.4.1
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.2
  google_fonts: 2.2.0
  page_transition: 2.0.4
  font_awesome_flutter: 10.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/alphaCoin.png
    - assets/sigmaCoin.png


